language: node_js
sudo: false
node_js:
  - 6.4
# NodeJS v4 requires gcc 4.8
env:
  - NODE_ENV=travis CXX="g++-4.8" CC="gcc-4.8"

#matrix:
  #allow_failures:
    #- node_js: 5

#services:
  #- mongodb
# gcc 4.8 requires ubuntu-toolchain-r-test

before_install:
  - npm i nsp -g
  - npm install gulpjs/gulp-cli -g

after_script:
  - nsp audit-package
  - npm run coverage
